all:
	c++ -std=c++11 -pthread ./main.cpp ./CsvFiles/CsvFile.cpp ./DoTask/DoTask.cpp ./FrameWork/FrameWork.hpp ./ReadWriteLive/ReadWriteLive.cpp -o TaskBin 
clean:
	rm -rf ./main.o ./CsvFiles/CsvFile.o ./DoTask/DoTask.o  ./ReadWriteLive/ReadWriteLive.o  TaskBin 
